### ISSUE TITLE
Php version issue?

### ISSUE THREAD

**Issue by Hessel91** [TheJackMachine/barba#2]
Hi after installation the path: backend/system/updates return an error. 
Is there a solution other than downgrading my php version?

![2020-12-02_12-22-40](https://user-images.githubusercontent.com/7326568/100866572-26c4bb80-3499-11eb-909d-0bfbe81d1d53.png)

**Comment by TheJackMachine** [comment]
Strange, can you show me the full backtrace off this error ?
Barba plugin seems to not be the problem but if you show me the full backtrace i can review the code.

**Comment by Hessel91** [comment]
yes when I delete the plugin files with ftp then updates page in the backend is available again. 

`Symfony\Component\Debug\Exception\FatalThrowableError: Unsupported operand types in /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/system/classes/SettingsManager.php:130
Stack trace:
#0 [internal function]: System\Classes\SettingsManager->System\Classes\{closure}(Object(stdClass), Object(stdClass))
#1 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/system/classes/SettingsManager.php(131): usort(Array, Object(Closure))
#2 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/system/classes/SettingsManager.php(163): System\Classes\SettingsManager->loadItems()
#3 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/system/ServiceProvider.php(389): System\Classes\SettingsManager->listItems('system')
#4 [internal function]: System\ServiceProvider->System\{closure}(Object(Backend\Classes\NavigationManager))
#5 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/october/rain/src/Events/Dispatcher.php(233): call_user_func_array(Object(Closure), Array)
#6 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/october/rain/src/Events/Dispatcher.php(197): October\Rain\Events\Dispatcher->dispatch('backend.menu.ex...', Array, false)
#7 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): October\Rain\Events\Dispatcher->fire('backend.menu.ex...', Array)
#8 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/backend/classes/NavigationManager.php(91): Illuminate\Support\Facades\Facade::__callStatic('fire', Array)
#9 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/backend/classes/NavigationManager.php(350): Backend\Classes\NavigationManager->loadItems()
#10 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/backend/classes/NavigationManager.php(508): Backend\Classes\NavigationManager->listMainMenuItems()
#11 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Backend\Classes\NavigationManager->getActiveMainMenuItem()
#12 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/backend/layouts/_mainmenu.htm(2): Illuminate\Support\Facades\Facade::__callStatic('getActiveMainMe...', Array)
#13 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/system/traits/ViewMaker.php(247): include('/home/branchevz...')
#14 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/system/traits/ViewMaker.php(156): Backend\Classes\Controller->makeFileContents('/home/branchevz...', Array)
#15 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/system/traits/ViewMaker.php(172): Backend\Classes\Controller->makeLayout('_mainmenu', Array)
#16 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/backend/layouts/default.htm(13): Backend\Classes\Controller->makeLayoutPartial('_mainmenu')
#17 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/system/traits/ViewMaker.php(247): include('/home/branchevz...')
#18 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/system/traits/ViewMaker.php(156): Backend\Classes\Controller->makeFileContents('/home/branchevz...', Array)
#19 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/system/traits/ViewMaker.php(128): Backend\Classes\Controller->makeLayout(NULL)
#20 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/system/traits/ViewMaker.php(110): Backend\Classes\Controller->makeViewContent('<div class="sco...')
#21 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/backend/classes/Controller.php(419): Backend\Classes\Controller->makeView('index')
#22 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/backend/classes/Controller.php(296): Backend\Classes\Controller->execPageAction('index', Array)
#23 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/backend/classes/BackendController.php(165): Backend\Classes\Controller->run('index', Array)
#24 [internal function]: Backend\Classes\BackendController->run('system/updates')
#25 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#26 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#27 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#28 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#29 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#30 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/modules/backend/classes/BackendController.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): Backend\Classes\BackendController->Backend\Classes\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#52 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#53 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#54 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#55 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#56 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(25): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#62 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#63 /home/branchevzorg/domains/brancheverenigingzorg.nl/public_html/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#64 {main}`

**Comment by TheJackMachine** [comment]
Hum ... ok thanks for the full backtrace.
I make a fresh install of october, 
After that i go to settings -> system -> install plugin, and i find the Barba plugin.
I install it ...

No problem at all.

So, difficult to debug if i can’t replicate the problem.
What is your PHPVersion ?
What is your October Version ?

I hope i can help you to install it.
